[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "https://phxpressurewash.com/*"
  to = "https://www.phxpressurewash.com/:splat"
  status = 301
  force = true
